version: '3.8'
services:
  boxdb:
    container_name: boxdb
    image: mariadb:11.0.2-jammy
    restart: always
    ports:
      - "3310:3306"
    environment:
      - MYSQL_DATABASE=blackbox
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=0624963644
      - MYSQL_ROOT_PASSWORD=0624963644
    volumes:
      - boxdb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      timeout: 3s
      interval: 5s
      retries: 10
    networks:
      - blackbox_network

volumes:
  boxdb_data:

networks:
  blackbox_network:
    driver: bridge