version: "3.8"
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - phpmyadmin_network

networks:
  phpmyadmin_network:
