/* eslint-disable no-prototype-builtins */
/* eslint-disable security/detect-object-injection */
/* eslint-disable @typescript-eslint/no-var-requires */
'use strict';

import path from "path";
import beautify from "js-beautify"
import { DMMF } from '@prisma/generator-helper/dist';
import { IConfig } from "./interfaces";
import { fileWrite } from "./utils/fileWrite";

const config: IConfig = require("../generator-config.json")
// const prismaJSON: DMMF.Model[] = require("@sicon/db/prisma/generated-nexus-json/prisma-models.json")
const fileToWrite: string = path.resolve(__dirname, config.mutationsInputsFile)

function generateRegularInputFields(scalars: DMMF.Field[]) {
	let fieldsTmp = ""
	for (const scalar of scalars) {
		const { name, type, kind, isRequired } = scalar
		const nullable = !isRequired
		const typeLowercase = typeof type === "string" ? type.charAt(0).toLowerCase() + type.slice(1) : ""
		if (kind === "scalar") {  // && name  !== "id" ignore id in payload because its auto generated by prisma
			fieldsTmp += `t${nullable ? ".nullable" : ""}.${typeLowercase}("${name}")\n`
		}
		if (kind === "enum") {
			fieldsTmp += `t${nullable ? ".nullable" : ""}.field("${name}", {
							type: "${type}"
						})\n`
		}
	}
	return fieldsTmp
}

function generateInputConstant(model: DMMF.Model) {
	const modelName = model.name
	const modelNameUpper = modelName.charAt(0).toUpperCase() + modelName.slice(1)

	// use regular fields from database
	const regularFields = model.fields
	const regularFieldsTmp = generateRegularInputFields(regularFields)

	return `\nexport const ${modelNameUpper}Input = inputObjectType({
				name: "${modelNameUpper}Input",
				definition(t) {
					${regularFieldsTmp}
				}
			})\n`
}

export async function generateMutationInputs(models: DMMF.Model[]) {
	let inputs = ""
	let constants = ""

	if (Array.isArray(models)) {
		for (const model of models) {
			// build input if not excluded from config
			if (!config.excludeWhereInputs.includes(model.name)) {
				constants += generateInputConstant(model)
			}
		}
	}

	inputs = `import { inputObjectType } from "nexus"\n${constants}\n`

	const formatted = beautify.js(inputs, {
		indent_size: 4,
		indent_with_tabs: true,
		space_in_empty_paren: true,
		brace_style: "preserve-inline"
	})

	await fileWrite(fileToWrite, formatted)
}

// ******** FOR DEBUG ONLY *********
// 1. Uncomment line 13 to use prismaJSON directly from prisma generated JSON file
// 2. Uncomment this line bellow to call it with: npm run dev:inputs
// generateQueryInputs(prismaJSON)
